# Generated by Django 5.0.2 on 2024-03-03 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_class', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('host_country', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('govt_order', models.CharField(max_length=150)),
                ('govt_order_upload', models.FileField(upload_to='govt_orders/')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('sainik', 'Sainik'), ('lcpl', 'Lance Corporal'), ('cpl', 'Corporal'), ('sgt', 'Sergeant'), ('wo', 'Warrant Officer'), ('swo', 'Senior Warrant Officer'), ('mwo', 'Master Warrant Officer'), ('cadet', 'Cadet Officer'), ('2_lt', '2 Lieutenant'), ('lt', 'Lieutenant'), ('capt', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier General'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General'), ('2_lt_afns', '2 Lieutenant AFNS'), ('lt_afns', 'Lieutenant AFNS'), ('capt_afns', 'Captain AFNS'), ('major_afns', 'Major AFNS'), ('lieutenant_colonel_afns', 'Lieutenant Colonel AFNS'), ('sailor', 'Sailor'), ('leading_seaman', 'Leading Seaman'), ('petty_officer', 'Petty Officer'), ('chief_petty_officer', 'Chief Petty Officer'), ('sub_lieutenant', 'Sub Lieutenant'), ('lieutenant_commander', 'Lieutenant Commander'), ('commander', 'Commander'), ('captain_navy', 'Captain'), ('rear_admiral', 'Rear Admiral'), ('vice_admiral', 'Vice Admiral'), ('admiral', 'Admiral'), ('airman', 'Airman'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('flight_sergeant', 'Flight Sergeant'), ('warrant_officer', 'Warrant Officer'), ('pilot_officer', 'Pilot Officer'), ('flying_officer', 'Flying Officer'), ('flight_lieutenant', 'Flight Lieutenant'), ('squadron_leader', 'Squadron Leader'), ('wing_commander', 'Wing Commander'), ('group_captain', 'Group Captain'), ('air_commodore', 'Air Commodore'), ('air_vice_marshal', 'Air Vice Marshal'), ('air_marshal', 'Air Marshal'), ('air_chief_marshal', 'Air Chief Marshal'), ('civilian', 'Civilian')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('army', 'Army'), ('navy', 'Navy'), ('air_force', 'Air Force')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('vacancies_offered', models.PositiveIntegerField(default=1)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1900)])),
                ('vacancies_accepted_army', models.PositiveIntegerField(default=1)),
                ('vacancies_accepted_navy', models.PositiveIntegerField(default=1)),
                ('vacancies_accepted_air', models.PositiveIntegerField(default=1)),
                ('vacancies_regretted', models.PositiveIntegerField(default=0)),
                ('fin_offer', models.CharField(choices=[('gratis', 'Gratis'), ('non-gratis', 'Non-Gratis'), ('partial-gratis', 'Partial-Gratis'), ('reciprocal', 'Reciprocal')], default='gratis', max_length=20)),
                ('ff_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.participant')),
            ],
        ),
    ]
