# Generated by Django 4.2.10 on 2024-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficersandStaffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('sainik', 'Sainik'), ('lcpl', 'Lance Corporal'), ('cpl', 'Corporal'), ('sgt', 'Sergeant'), ('wo', 'Warrant Officer'), ('swo', 'Senior Warrant Officer'), ('mwo', 'Master Warrant Officer'), ('cadet', 'Cadet Officer'), ('2_lt', '2 Lieutenant'), ('lt', 'Lieutenant'), ('capt', 'Captain'), ('major', 'Major'), ('lieutenant_colonel', 'Lieutenant Colonel'), ('colonel', 'Colonel'), ('brigadier', 'Brigadier General'), ('major_general', 'Major General'), ('lieutenant_general', 'Lieutenant General'), ('general', 'General'), ('2_lt_afns', '2 Lieutenant AFNS'), ('lt_afns', 'Lieutenant AFNS'), ('capt_afns', 'Captain AFNS'), ('major_afns', 'Major AFNS'), ('lieutenant_colonel_afns', 'Lieutenant Colonel AFNS'), ('sailor', 'Sailor'), ('leading_seaman', 'Leading Seaman'), ('petty_officer', 'Petty Officer'), ('chief_petty_officer', 'Chief Petty Officer'), ('sub_lieutenant', 'Sub Lieutenant'), ('lieutenant_commander', 'Lieutenant Commander'), ('commander', 'Commander'), ('captain_navy', 'Captain'), ('rear_admiral', 'Rear Admiral'), ('vice_admiral', 'Vice Admiral'), ('admiral', 'Admiral'), ('airman', 'Airman'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('flight_sergeant', 'Flight Sergeant'), ('warrant_officer', 'Warrant Officer'), ('pilot_officer', 'Pilot Officer'), ('flying_officer', 'Flying Officer'), ('flight_lieutenant', 'Flight Lieutenant'), ('squadron_leader', 'Squadron Leader'), ('wing_commander', 'Wing Commander'), ('group_captain', 'Group Captain'), ('air_commodore', 'Air Commodore'), ('air_vice_marshal', 'Air Vice Marshal'), ('air_marshal', 'Air Marshal'), ('air_chief_marshal', 'Air Chief Marshal'), ('civilian', 'Civilian')], max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('army', 'Army'), ('navy', 'Navy'), ('air_force', 'Air Force')], max_length=20)),
                ('staffstatus', models.CharField(choices=[('commissioned_officer', 'Commissioned Officer'), ('jco', 'JCO'), ('other_rank', 'Other Rank'), ('civilian', 'Civilian')], max_length=50)),
                ('dateofjoin', models.DateField()),
                ('dateofpostedout', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
