# Generated by Django 4.2.10 on 2024-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_officersandstaffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officersandstaffs',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
